### ISSUE TITLE
Any recognition ?

### ISSUE THREAD

**Issue by enzolutions** [grasmash/yaml-cli#1]
HI @grasmash 

I am wondering if you get inspired by Drupal Console YAML commands? If you get, could you consider maybe put a recognition in README page.

I already started a process to split in a separate repository at https://github.com/hechoendrupal/drupal-console-yaml but I think we could close that repo in behalf these commands if works well with Drupal Console, I am planning to test your commands at the beginning of next week top.

Happy coding.

**Comment by grasmash** [comment]
@enzolutions Yes, the inspiration for this tool did come from the commands in Drupal Console. I've added a reference in README.md. https://github.com/grasmash/yaml-cli/commit/76422d168bcbaa7038920102fe1870d60b190820

Let me know if I can help with integration, or if you're interested in collaborating on this project.
