### ISSUE TITLE
Set integers in shell script

### ISSUE THREAD

**Issue by adam-delaney** [grasmash/yaml-cli#11]
I'm trying to set a timestamp in a shell script however it sets the value as a string. Is there a way to set it as an int?
Here is my example:
```
timestamp=$(date +"%s")
./vendor/bin/yaml-cli update:value some.yml timestamp $timestamp
```

**Comment by grasmash** [comment]
I could add an option like —type=int

**Comment by grasmash** [comment]
You can now do this with `./vendor/bin/yaml-cli update:value some.yml timestamp $timestamp --type=int`
