### ISSUE TITLE
set:key command

### ISSUE THREAD

**Issue by bobbygryzynger** [grasmash/yaml-cli#3]
One feature that came up as I've been working on [BLT #1005](https://github.com/acquia/blt/pull/1005) that would be nice to have is a command like: 
```
yaml-cli set:key key.nested [optional-value]
```
Is there currently any way to achieve this? I settled for simply `echo`-ing in the missing keys where need-be, but this wouldn't work well with nested keys.

**Comment by grasmash** [comment]
Have you tried `yaml-cli update:value file.yml key.nested value` ?

**Comment by grasmash** [comment]
Closing as I believe this is a supported feature.

**Comment by bobbygryzynger** [comment]
If I run the following on an existing but empty file:
```sh
vendor/bin/yaml-cli update:value test.yml foo.bar jar
```

I get the following output:
```sh
The file test.yml is empty.
```
I guess that I would expect that all required values would be created in this case.
